// Automatically generated by MockGen. DO NOT EDIT!
// Source: Request.go

package pelau

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Request interface
type MockRequest struct {
	ctrl     *gomock.Controller
	recorder *_MockRequestRecorder
}

// Recorder for MockRequest (not exported)
type _MockRequestRecorder struct {
	mock *MockRequest
}

func NewMockRequest(ctrl *gomock.Controller) *MockRequest {
	mock := &MockRequest{ctrl: ctrl}
	mock.recorder = &_MockRequestRecorder{mock}
	return mock
}

func (_m *MockRequest) EXPECT() *_MockRequestRecorder {
	return _m.recorder
}

func (_m *MockRequest) Param(_param0 int) string {
	ret := _m.ctrl.Call(_m, "Param", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockRequestRecorder) Param(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Param", arg0)
}

func (_m *MockRequest) Value(_param0 string) string {
	ret := _m.ctrl.Call(_m, "Value", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockRequestRecorder) Value(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Value", arg0)
}

func (_m *MockRequest) Decode(mime string, i interface{}) error {
	ret := _m.ctrl.Call(_m, "Decode", mime, i)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRequestRecorder) Decode(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Decode", arg0, arg1)
}

func (_m *MockRequest) Raw(_param0 func(*ModifiedRequest)) Request {
	ret := _m.ctrl.Call(_m, "Raw", _param0)
	ret0, _ := ret[0].(Request)
	return ret0
}

func (_mr *_MockRequestRecorder) Raw(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Raw", arg0)
}
