// Automatically generated by MockGen. DO NOT EDIT!
// Source: Response.go

package pelau

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Response interface
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *_MockResponseRecorder
}

// Recorder for MockResponse (not exported)
type _MockResponseRecorder struct {
	mock *MockResponse
}

func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &_MockResponseRecorder{mock}
	return mock
}

func (_m *MockResponse) EXPECT() *_MockResponseRecorder {
	return _m.recorder
}
