// Automatically generated by MockGen. DO NOT EDIT!
// Source: Route.go

package pelau

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Route interface
type MockRoute struct {
	ctrl     *gomock.Controller
	recorder *_MockRouteRecorder
}

// Recorder for MockRoute (not exported)
type _MockRouteRecorder struct {
	mock *MockRoute
}

func NewMockRoute(ctrl *gomock.Controller) *MockRoute {
	mock := &MockRoute{ctrl: ctrl}
	mock.recorder = &_MockRouteRecorder{mock}
	return mock
}

func (_m *MockRoute) EXPECT() *_MockRouteRecorder {
	return _m.recorder
}

func (_m *MockRoute) Query(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "Query", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockRouteRecorder) Query(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Query", arg0)
}

func (_m *MockRoute) Execute(_param0 *Request, _param1 *Response) {
	_m.ctrl.Call(_m, "Execute", _param0, _param1)
}

func (_mr *_MockRouteRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Execute", arg0, arg1)
}
