// Automatically generated by MockGen. DO NOT EDIT!
// Source: Route.go

package pelau

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Route interface
type MockRoute struct {
	ctrl     *gomock.Controller
	recorder *_MockRouteRecorder
}

// Recorder for MockRoute (not exported)
type _MockRouteRecorder struct {
	mock *MockRoute
}

func NewMockRoute(ctrl *gomock.Controller) *MockRoute {
	mock := &MockRoute{ctrl: ctrl}
	mock.recorder = &_MockRouteRecorder{mock}
	return mock
}

func (_m *MockRoute) EXPECT() *_MockRouteRecorder {
	return _m.recorder
}

func (_m *MockRoute) Query(_param0 string, _param1 Request, _param2 Response) bool {
	ret := _m.ctrl.Call(_m, "Query", _param0, _param1, _param2)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockRouteRecorder) Query(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Query", arg0, arg1, arg2)
}
