// Automatically generated by MockGen. DO NOT EDIT!
// Source: Router.go

package pelau

import (
	http "net/http"
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Router interface
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *_MockRouterRecorder
}

// Recorder for MockRouter (not exported)
type _MockRouterRecorder struct {
	mock *MockRouter
}

func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &_MockRouterRecorder{mock}
	return mock
}

func (_m *MockRouter) EXPECT() *_MockRouterRecorder {
	return _m.recorder
}

func (_m *MockRouter) Use(_param0 MiddleWare) Router {
	ret := _m.ctrl.Call(_m, "Use", _param0)
	ret0, _ := ret[0].(Router)
	return ret0
}

func (_mr *_MockRouterRecorder) Use(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Use", arg0)
}

func (_m *MockRouter) Get(_param0 Route) Router {
	ret := _m.ctrl.Call(_m, "Get", _param0)
	ret0, _ := ret[0].(Router)
	return ret0
}

func (_mr *_MockRouterRecorder) Get(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0)
}

func (_m *MockRouter) Post(_param0 Route) Router {
	ret := _m.ctrl.Call(_m, "Post", _param0)
	ret0, _ := ret[0].(Router)
	return ret0
}

func (_mr *_MockRouterRecorder) Post(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Post", arg0)
}

func (_m *MockRouter) Put(_param0 Route) Router {
	ret := _m.ctrl.Call(_m, "Put", _param0)
	ret0, _ := ret[0].(Router)
	return ret0
}

func (_mr *_MockRouterRecorder) Put(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Put", arg0)
}

func (_m *MockRouter) Delete(_param0 Route) Router {
	ret := _m.ctrl.Call(_m, "Delete", _param0)
	ret0, _ := ret[0].(Router)
	return ret0
}

func (_mr *_MockRouterRecorder) Delete(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete", arg0)
}

func (_m *MockRouter) Head(_param0 Route) Router {
	ret := _m.ctrl.Call(_m, "Head", _param0)
	ret0, _ := ret[0].(Router)
	return ret0
}

func (_mr *_MockRouterRecorder) Head(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Head", arg0)
}

func (_m *MockRouter) Bind(_param0 string, _param1 BindFunc) {
	_m.ctrl.Call(_m, "Bind", _param0, _param1)
}

func (_mr *_MockRouterRecorder) Bind(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Bind", arg0, arg1)
}

func (_m *MockRouter) ServeHTTP(_param0 http.ResponseWriter, _param1 *http.Request) {
	_m.ctrl.Call(_m, "ServeHTTP", _param0, _param1)
}

func (_mr *_MockRouterRecorder) ServeHTTP(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ServeHTTP", arg0, arg1)
}
